Tienda/Controllers/GestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tienda.Models;
using System.Data.Entity;
using System.Net;
using Newtonsoft.Json.Linq;

namespace Tienda.Controllers
{
    [Authorize(Roles = Rol.Admin + "," + Rol.Vendedor)]
    public class GestionController : Controller
    {
        private ApplicationDbContext _context = new ApplicationDbContext();
        // GET: Gestion
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Detalles()
        {
            var _empresa = _context.Empresas.ToList();
            return View();
        }

        public ActionResult Crud(int id = 0)
        {
            if (id == 0)
            {
                var _empresaInDb = _context.Empresas.Single();

                return View(_empresaInDb);
            }
            return View();
        }

        public ActionResult Guardar(Empresa empresa)
        {
            if (!ModelState.IsValid)
                return View("Crud", empresa);

            var _empresaInDb = _context.Empresas.Single();
            _empresaInDb.RazonSocial = empresa.RazonSocial;
            _empresaInDb.RepresentanteLegal = empresa.RepresentanteLegal;
            _empresaInDb.Telefono = empresa.Telefono;
            _empresaInDb.Giro = empresa.Giro;
            _empresaInDb.Email = empresa.Email;
            _empresaInDb.Direccion = empresa.Direccion;
            _empresaInDb.Comuna = empresa.Comuna;
            _empresaInDb.Ciudad = empresa.Ciudad;

            _context.SaveChanges();

            return RedirectToAction("Index", "gestion");
        }

        public ActionResult Mensajes()
        {
            var mensaje = _context.Contactos.ToList();
            return View(mensaje);
        }

        public ActionResult Cotizaciones()
        {
            var _cotizaciones = _context.Cotizaciones.ToList();
            return View(_cotizaciones);
        }

        public ActionResult Reportes()
        {
            return View();
        }

        public class chart
        {
            public string nombre { get; set; }
            public int entero1 { get; set; }
            public int entero2 { get; set; }
            public int entero3 { get; set; }
            public double valor { get; set; }
            public double decimal1 { get; set; }
            public double decimal2 { get; set; }
            public double decimal3 { get; set; }
            public string color { get; set; }
        }

        public JsonResult Get(int a, int b)
        {
            List<chart> lista = new List<chart>();
            switch (a)
            {
                case 1:
                    VentasYarriendosTotales(lista, b);
                    break;
                case 2:
                    PorcentajeLocalVsOnline(lista, b);
                    break;
                case 3:
                    VentasVsArriendos(lista, b);
                    break;
                case 4:
                    for (int i = 1; i <= 12; i++)
                    {
                        var suma = 0.0;
                        try
                        {
                            suma = _context.DetalleVentas.Where(x => x.Venta.Fecha.Month == i).Sum(x => x.Precio);
                        }
                        catch (Exception)
                        {

                            suma = 0;
                        }
                        var asd = i;

                        string[] meses = { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Nobiembre", "Diciembre" };

                        lista.Add(new chart { nombre = meses[asd - 1], valor = suma });
                    }
                    break;
                case 5:
                    for (int i = 1; i <= 12; i++)
                    {
                        var suma = 0.0;
                        try
                        {
                            suma = _context.DetalleAdquisiciones.Where(x => x.Adquisicion.Fecha.Month == i).Sum(x => x.Precio);
                        }
                        catch (Exception)
                        {

                            suma = 0;
                        }
                        var asd = i;

                        string[] meses = { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Nobiembre", "Diciembre" };

                        lista.Add(new chart { nombre = meses[asd - 1], valor = suma });
                    }
                    break;
                default:
                    PorcentajeLocalVsOnline(lista, b);
                    break;
            }

            return Json(lista, JsonRequestBehavior.AllowGet);
        }
        private void cantidadventa_año(List<chart> lista)
        {


        }

        private void PorcentajeLocalVsOnline(List<chart> lista, int b)
        {
            var consultalocal = 0;
            var consultaonline = 0;
            if (b == 0)
            {
                consultalocal = _context.Ventas.Include(x => x.DetalleVenta).Where(x => x.EsOnline == false).Count();
                consultaonline = _context.Ventas.Include(x => x.DetalleVenta).Where(x => x.EsOnline == true).Count();
            }
            else
            {
                consultalocal = _context.Ventas.Include(x => x.DetalleVenta).Where(x => x.EsOnline == false).Where(x => x.Fecha.Month == b).Count();
                consultaonline = _context.Ventas.Include(x => x.DetalleVenta).Where(x => x.EsOnline == true).Where(x => x.Fecha.Month == b).Count();
            }

            lista.Add(new chart { nombre = "Ventas Locales", valor = consultalocal });
            lista.Add(new chart { nombre = "Ventas Online", valor = consultaonline });
        }

        private void VentasVsArriendos(List<chart> lista, int b)
        {
            var consultaarriendo = 0;
            var consultaVentas = 0;
            if (b == 0)
            {
                consultaarriendo = _context.Arriendos.Include(x => x.DetalleArriendo).Count();
                consultaVentas = _context.Ventas.Include(x => x.DetalleVenta).Count();
            }
            else
            {
                consultaarriendo = _context.Arriendos.Include(x => x.DetalleArriendo).Where(x => x.FechaInicio.Month == b).Count();
                consultaVentas = _context.Ventas.Include(x => x.DetalleVenta).Where(x => x.Fecha.Month == b).Count();
            }

            lista.Add(new chart { nombre = "Ventas", valor = consultaVentas });
            lista.Add(new chart { nombre = "Arriendos", valor = consultaarriendo });
        }

        private void VentasYarriendosTotales(List<chart> lista, int b)
        {
            Random r = new Random();
            string[] colores = { "#C0392B ", "#E74C3C", "#9B59B6", "#8E44AD", "#2980B9", "#3498DB", "#1ABC9C", "#16A085", "#27AE60", "#2ECC71", "#F1C40F", "#F39C12", "#E67E22", "#D35400" };
            var consultav = _context.DetalleVentas.Include(x => x.Producto).ToList();
            var consultaa = _context.DetalleArriendos.Include(x => x.Producto).ToList();

            if (b != 0)
            {
                consultav = _context.DetalleVentas.Include(x => x.Producto).Where(x => x.Venta.Fecha.Month == b).ToList();
                consultaa = _context.DetalleArriendos.Include(x => x.Producto).Where(x => x.Arriendo.FechaInicio.Month == b).ToList();
            }



            var consultap = _context.Productos.Where(x => x.TipoProductoId == Tipo_negocio.Seguridad).ToList();
            foreach (var item in consultap)
            {
                var a = consultav.Where(x => x.ProductoId == item.Id).Sum(x => x.Cantidad);
                var c = consultaa.Where(x => x.ProductoId == item.Id).Sum(x => x.Cantidad);
                lista.Add(new chart
                {
                    nombre = item.Nombre,
                    entero1 = a + c,
                    color = colores[r.Next(colores.Length)]
                });
            }
        }


    }
}

Tienda/Views/Gestion/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLteLayout.cshtml";
}
<section class="content">
    <ol class="breadcrumb box">
        <li>Inicio</li>
    </ol>
    <!-- Main content -->
    
        <div class="row">

            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3>@ViewData["CantidadVentas"]</h3>
                        <p>Ventas Totales</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>

                    <a href="@Url.Action("Index","Ventas")" class="small-box-footer">Ver mas <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>@ViewData["CantidadArriendos"]</h3>
                        <p>Arriendos pendientes</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-get-pocket"></i>
                    </div>
                    <a href="@Url.Action("Index","Arriendos")" class="small-box-footer">Ver mas <i class="fa fa-arrow-circle-right"></i></a>

                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-yellow">
                    <div class="inner">
                        <h3>@ViewData["CantidadCompras"]</h3>
                        <p>Adquisiciones Totales</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-shopping-cart"></i>
                    </div>
                    <a href="@Url.Action("Index","Adquisiciones")" class="small-box-footer">Ver mas <i class="fa fa-arrow-circle-right"></i></a>

                </div>
            </div>

            @*   <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-red">
                        <div class="inner">
                            <h3>@ViewData["CantidadMensajes"]</h3>
                            <p>Mensajes no Leidos</p>
                        </div>
                        <div class="icon">
                            <i class="fa fa-inbox"></i>
                        </div>
                        <a href="@Url.Action("Index", "Contacto")" class="small-box-footer">Ver mas <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            *@
            <!-- ./col -->
        </div>
    </section>

Tienda/Views/Gestion/Mensajes.cshtml
@model IEnumerable<Tienda.Models.Contacto>
@{
    ViewBag.Title = "Mensajes";
    Layout = "~/Views/Shared/_AdminLteLayout.cshtml";
}

<section class="content">
    <ol class="breadcrumb box">
        <li><a href="@Url.Action("Index","Gestion")">Inicio</a></li>
        <li class="active">Mensajes</li>
    </ol>
    <div class="box">
        <div class="box-header">
            <div class="box-title">
                <small>Mensajes</small>
            </div>
            <div class="box-tools">

            </div>
        </div>
        <div class="box-body table-responsive">
            <br />
            <table id="Mensajes" class="table table-bordered">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Id)

                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Nombre)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Telefono)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.Correo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Contenido)
                        </th>                    
                        <th></th>
                    </tr>
                </thead>
                <tbody>
           
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Telefono)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Correo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Contenido)
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="box-footer">

        </div>
    </div>
</section>


@section Scripts{

    <script>
        $(document).ready(function () {
            $("#Mensajes").DataTable();
        });
    </script>
}

Tienda/Views/Gestion/Reportes.cshtml
@{
    ViewBag.Title = "Reportes";
    Layout = "~/Views/Shared/_AdminLteLayout.cshtml";
}

<section class="content">

    <ul class="nav nav-pills nav-justified box">
        <li role="presentation" id="boton1"><a>Productos VA</a></li>
        <li role="presentation" id="boton2"><a>Ventas Local VS Online</a></li>
        <li role="presentation" id="boton3"><a>Ventas Vs Arriendos</a></li>
        <li role="presentation" id="boton4"><a>Ventas x Mes</a></li>
        <li role="presentation" id="boton5"><a>Adquisiciones x Mes</a></li>
    </ul>
  
    <select id="meses">
        <option value="0">Global</option>
        <option value="1">Enero</option>
        <option value="2">Febrero</option>
        <option value="3">Marzo</option>
        <option value="4">Abril</option>
        <option value="5">Mayo</option>
        <option value="6">Junio</option>
        <option value="7">Julio</option>
        <option value="8">Agosto</option>
        <option value="9">Septiembre</option>
        <option value="10">Octubre</option>
        <option value="11">Noviembre</option>
        <option value="12">Diciembre</option>
    </select>
    <br />
    <div id="chartdiv"></div>

</section>
@section scripts
{
    <style>
        #chartdiv {
            width: 100%;
            height: 500px;
        }
        .amcharts-export-menu-top-right {
            top: 10px;
            right: 0;
        }
    </style>
    <script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
    <script src="https://www.amcharts.com/lib/3/serial.js"></script>
    <script src="https://www.amcharts.com/lib/3/pie.js"></script>
    <script src="https://www.amcharts.com/lib/3/plugins/export/export.min.js"></script>
    <link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />
    <script src="https://www.amcharts.com/lib/3/themes/light.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            var b = 0;
            $('#boton1').addClass("active");
            GetReporte(1);
            $('#boton1').on('click', function () {
                $("li").removeClass("active");
                $(this).addClass("active");
                b = $("#meses").val();
                GetReporte(1,b);
            });
            $('#boton2').on('click', function () {
                $("li").removeClass("active");
                $(this).addClass("active");
                b = $("#meses").val();
                GetReporte(2,b);
            });
            $('#boton3').on('click', function () {
                $("li").removeClass("active");
                $(this).addClass("active");
                b = $("#meses").val();
                GetReporte(3,b);
            });    
            $('#boton4').on('click', function () {
                $("li").removeClass("active");
                $(this).addClass("active");
                b = 0;
                GetReporte(4, b);
            }); 
            $('#boton5').on('click', function () {
                $("li").removeClass("active");
                $(this).addClass("active");
                b = 0;
                GetReporte(5, b);
            }); 
        });
      
        function GetReporte(a,b=0)
        {
            $.ajax({
                type: 'POST',
                contentType: 'application/json; charset=utf-8',
                url: '@Url.Action("Get")',
                data: "{'a':'" + a + "','b':'" + b + "'}",
                success: function (data) {
                    switch (a) {
                        case 1:
                            Reporte_CDP_V_A(data);
                            break;
                        case 2:
                            Reporte_V_OnlineLocal(data);
                            break;
                        case 3:
                            Reporte_VA(data);
                            break;      
                        case 4:
                            myreporte(data)
                            break;  
                        case 5:
                            myreporte(data)
                            break;
                        default:
                            Reporte_V_OnlineLocal(data);
                            break;
                    }
                },
                error: function (data) {
                    alert("Ocurrio un Error, Intente nuevamente");
                }
            });
        }

        function Reporte_CDP_V_A(data) {
            var chart = AmCharts.makeChart("chartdiv", {
                "type": "serial",
                "theme": "light",
                "titles": [{
                    "text": "Productos"
                }, {
                    "text": "Total de productos en ventas",
                    "bold": false
                }],
                "marginRight": 70,
                "dataProvider": data,
                "startDuration": 1,
                "graphs": [{
                    "balloonText": "<b>[[category]]: [[value]]</b>",
                    "fillColorsField": "color",
                    "fillAlphas": 0.9,
                    "lineAlpha": 0.2,
                    "type": "column",
                    "valueField": "entero1"
                }],
                "valueAxes": [{
                    "title": "Cantidad"
                }],
                "chartCursor": {
                    "categoryBalloonEnabled": false,
                    "cursorAlpha": 0,
                    "zoomable": false
                },
                "categoryField": "nombre",
                "categoryAxis": {
                    "gridPosition": "start",
                    "labelRotation": 45
                },
                "export": {
                    "enabled": true,
                    
                }

            });
        }
        function Reporte_V_OnlineLocal(data)
        {
            var chart = AmCharts.makeChart("chartdiv", {
                "type": "pie",
                "titles": [{
                    "text": "Ventas"
                }, {
                    "text": "Porcentaje de Ventas Local y Online",
                    "bold": false
                }],
                "theme": "light",
                "dataProvider": data,
                "valueField": "valor",
                "titleField": "nombre",
                "outlineAlpha": 0.4,
                "depth3D": 15,
                "balloonText": "[[title]]<br><span style='font-size:14px'><b>[[value]]</b> ([[percents]]%)</span>",
                "angle": 30,
                "export": {
                    "enabled": true
                }
            });
        }

        function Reporte_VA(data) {
            var chart = AmCharts.makeChart("chartdiv", {
                "type": "pie",
                "theme": "light",
                "titles": [{
                    "text": "Ventas | Arriendos"
                }, {
                    "text": "Porcentaje de Ventas Vs Arriendos",
                    "bold": false
                }],
                "dataProvider": data,
                "valueField": "valor",
                "titleField": "nombre",
                "outlineAlpha": 0.4,
                "depth3D": 15,
                "balloonText": "[[title]]<br><span style='font-size:14px'><b>[[value]]</b> ([[percents]]%)</span>",
                "angle": 30,
                "export": {
                    "enabled": true
                }
            });
        }

        function Reporte2(data)
        {
            var chart = AmCharts.makeChart("chartdiv", {
                "theme": "light",
                "type": "serial",
                "dataProvider": data,
                "valueAxes": [{
                    "stackType": "3d",
                    "unit": "%",
                    "position": "left",
                    "title": "GDP growth rate",
                }],
                "startDuration": 1,
                "graphs": [{
                    "balloonText": "GDP grow in [[category]] (2004): <b>[[value]]</b>",
                    "fillAlphas": 0.9,
                    "lineAlpha": 0.2,
                    "title": "2004",
                    "type": "column",
                    "valueField": "entero2"
                }, {
                    "balloonText": "GDP grow in [[category]] (2005): <b>[[value]]</b>",
                    "fillAlphas": 0.9,
                    "lineAlpha": 0.2,
                    "title": "2005",
                    "type": "column",
                    "valueField": "entero1"
                }],
                "plotAreaFillAlphas": 0.1,
                "depth3D": 17,
                "angle": 41,
                "categoryField": "nombre",
                "categoryAxis": {
                    "gridPosition": "start"
                },
                "export": {
                    "enabled": true
                }
            });
            jQuery('.chart-input').off().on('input change', function () {
                var property = jQuery(this).data('property');
                var target = chart;
                chart.startDuration = 0;

                if (property == 'topRadius') {
                    target = chart.graphs[0];
                    if (this.value == 0) {
                        this.value = undefined;
                    }
                }

                target[property] = this.value;
                chart.validateNow();
            });
        }

        function reportventas(data)
        {

            var chart = AmCharts.makeChart("chartdiv", {
                "type": "serial",
                "theme": "light",
                "dataProvider": data,
                "valueAxes": [{
                    "gridColor": "#FFFFFF",
                    "gridAlpha": 0.2,
                    "dashLength": 0
                }],
                "gridAboveGraphs": true,
                "startDuration": 1,
                "graphs": [{
                    "balloonText": "[[category]]: <b>[[value]]</b>",
                    "fillAlphas": 0.8,
                    "lineAlpha": 0.2,
                    "type": "column",
                    "valueField": "visits"
                }],
                "chartCursor": {
                    "categoryBalloonEnabled": false,
                    "cursorAlpha": 0,
                    "zoomable": false
                },
                "categoryField": "country",
                "categoryAxis": {
                    "gridPosition": "start",
                    "gridAlpha": 0,
                    "tickPosition": "start",
                    "tickLength": 20
                },
                "export": {
                    "enabled": true
                }

            });
        }

        function myreporte(data)
        {
            var chart = AmCharts.makeChart("chartdiv", {
                "type": "serial",
                "theme": "light",
                "dataProvider": data,
                "valueAxes": [{
                    "gridColor": "#FFFFFF",
                    "gridAlpha": 0.2,
                    "dashLength": 0
                }],
                "gridAboveGraphs": true,
                "startDuration": 1,
                "graphs": [{
                    "balloonText": "[[category]]: <b>[[value]]</b>",
                    "fillAlphas": 0.8,
                    "lineAlpha": 0.2,
                    "type": "column",
                    "valueField": "valor"
                }],
                "chartCursor": {
                    "categoryBalloonEnabled": false,
                    "cursorAlpha": 0,
                    "zoomable": false
                },
                "categoryField": "nombre",
                "categoryAxis": {
                    "gridPosition": "start",
                    "gridAlpha": 0,
                    "tickPosition": "start",
                    "tickLength": 20
                },
                "export": {
                    "enabled": true
                }

            });
        }

        
    </script>
}